export interface BoxItem {
  id: string;
  name: string;
  category?: string;
}

export interface Box {
  id: string; // Unique identifier for the box, can be manually entered or generated
  qrCodeValue: string; // Data embedded in the QR code, typically the box ID
  photoDataUrl?: string; // Base64 data URL of the box contents' photo
  items: BoxItem[]; // List of items identified in the box
  manualDescription?: string; // User's manual notes about the box contents
  aiGeneratedTags?: string[]; // Tags generated by AI from the photo
  suggestedRoom?: string; // Room suggested by AI
  assignedRoom?: string; // Room manually assigned by the user
  createdAt: string; // ISO date string
}

export const ROOM_OPTIONS = [
  "Kitchen",
  "Living Room",
  "Dining Room",
  "Master Bedroom",
  "Bedroom 2",
  "Bedroom 3",
  "Office",
  "Bathroom 1",
  "Bathroom 2",
  "Garage",
  "Basement",
  "Attic",
  "Storage",
  "Utility Room",
  "Playroom",
  "Guest Room",
] as const;

export type Room = typeof ROOM_OPTIONS[number];
